-   id: check-undeclared
    name: FawltyDeps-undeclared
    description: "FawltyDeps: Check for undeclared dependencies"
    entry: fawltydeps --check-undeclared
    language: python
    files: ".*\\.py|ipynb"
    args:
      - --code
    pass_filenames: true
-   id: check-unused
    name: FawltyDeps-unused
    description: "FawltyDeps: Check for unused dependencies"
    entry: fawltydeps --check-unused
    language: python
    files: ".*\\.py|ipynb"
    pass_filenames: false
